services:
  backend:
    build: ./todoback
    ports:
      - '8080:8080'
    env_file:
      - .env
  frontend:
    build: ./todofront
    ports:
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
  db:
    env_file: .env
    image: mysql:8.0
    container_name: mysql
    ports:
      - '3307:3306'
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
