services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tododb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - todo-network
    command: --default-authentication-plugin=mysql_native_password

  todoback:
    build:
      context: ./todoback
      dockerfile: Dockerfile
    container_name: todo-backend
    restart: unless-stopped
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - todo-network
    volumes:
      - ./logs:/app/logs

  nginx:
    build:
      context: ./todofront
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - todo-network

volumes:
  mysql_data:
    driver: local

networks:
  todo-network:
    driver: bridge
