name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Images and Push to Docker Hub
        run: |
          set -euo pipefail
          IMAGE_TAG="$(git rev-parse --short HEAD)"
          docker build -t "qazqww/todoback" ./todoback
          docker push "qazqww/todoback"

      - name: Build Frontend Docker Images and Push to Docker Hub
        run: |
          set -euo pipefail
          IMAGE_TAG="$(git rev-parse --short HEAD)"
          docker build -t "qazqww/todofront" ./todofront
          docker push "qazqww/todofront"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
            set -euo pipefail

            cd /home/$EC2_USER/todoproject
            git fetch --all
            git reset --hard origin/main

            echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USER }}' --password-stdin
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans
            docker image prune -f
            "
